opt_in_rules: # some rules are only opt-in
# Prefer checking isEmpty over comparing count to zero
    - empty_count
    - empty_string
    - force_unwrapping
    - vertical_whitespace_between_cases
# Closure end should have the same indentation as the line that started it.
    - closure_end_indentation
# Closure expressions should have a single space inside each brace
    - closure_spacing
# All elements in a collection literal should be vertically aligned
    - collection_alignment
# Prefer checking isEmpty over comparing collection to an empty array or dictionary literal.
    - empty_collection_literal
# Number of associated values in an enum case should be low: 1
    - enum_case_associated_values_count
# Enums should be explicitly assigned their raw values
    - explicit_enum_raw_value
    - explicit_init

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - Brouser/Resources/Generations/R.generated.swift
    - Source/ExcludedFolder
    - Source/ExcludedFile.swift
    - Source/*/ExcludedFile.swift # Exclude files with a wildcard
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
    - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: error # implicitly
force_unwrapping: error
force_try:
    severity: error # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 200
# they can set both implicitly with an array
type_body_length:
    warning: 300 # warning
    error: 400 # error
# or they can set both explicitly
function_body_length:
    warning: 100
    error: 200
file_length:
    warning: 500
    error: 800
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
    min_length: 2 # only warning
    max_length: # warning and error
    warning: 40
    error: 50
    excluded: iPhone # excluded via string
    allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
    min_length: # only min_length
    warning: 1
    error: 1 # only error
    excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
